.PHONY: all clean

CFLGAS+=
LDFLAGS+=-lm     # link to math library

TARGET=train
TARGET2=test

all: $(TARGET) $(TARGET2) 
# type make/make all to compile train.c and test.c
clean:
	$(RM) $(TARGET) $(TARGET2)  # type make clean to remove the compiled file